<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Filter Column</name>
   <tag></tag>
   <elementGuidId>6032b64c-da49-4b69-b9f2-ed49db52c210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button' and contains(@class, 'ResultMonitoringIncoming_btn')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-round.Button_button__custom__bmibn.ResultMonitoringIncoming_btn__0gDZj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>622d6e3a-73c9-467e-a7f7-a8a135266aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>380accab-32ae-4c8f-b193-d94711915b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-round Button_button__custom__bmibn ResultMonitoringIncoming_btn__0gDZj</value>
      <webElementGuid>54ab46b8-5f74-420f-8443-e1c0057218f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>347382c4-ac7c-4743-afaf-867c39483c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout&quot;]/div[@class=&quot;Layout_layout-content__UoFx4&quot;]/section[@class=&quot;ant-layout Layout_layout-transition__tp-4e Layout_collapsed__Z9C94&quot;]/section[@class=&quot;ant-layout Layout_content__95Ydx&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;layout-wrapper&quot;]/div[@class=&quot;layout-content-wrapper&quot;]/div[@class=&quot;ResultMonitoringIncoming_header-wrapper__3Kb1i&quot;]/div[@class=&quot;ResultMonitoringIncoming_filter-download-wrapper__UFQh-&quot;]/div[2]/div[@class=&quot;Button_button__wrapper__QltLh&quot;]/button[@class=&quot;ant-btn ant-btn-round Button_button__custom__bmibn ResultMonitoringIncoming_btn__0gDZj&quot;]</value>
      <webElementGuid>7232cdd1-f926-4709-a79c-140ba6edff54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>bbf4a355-384d-47b1-8445-125b5463d649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/section/section/main/div/div/div[2]/div/div[2]/div/button</value>
      <webElementGuid>f29a482e-b269-4c11-b92a-3bd814636b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pelanggan'])[1]/following::button[1]</value>
      <webElementGuid>024a85d4-cf6d-409a-aade-84a373fcd070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring Incoming Payment'])[1]/following::button[1]</value>
      <webElementGuid>9efd13f4-85f4-4e19-bc4b-ea8bdfbe1e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>74a9841c-99e7-44f1-901e-60a6ca83bc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>b247a6ee-4269-4b3f-a467-3d0661847baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>680bb66d-12c5-4868-8e52-042620552c19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
