<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login Astra Logo</name>
   <tag></tag>
   <elementGuidId>764ca5cc-c0e4-41cc-ab7b-0845e8f23c6f</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Assist - Astra Motor Integrated System/img_Login Sales Office_Login_logo__37kBD.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src, '/static/media/logo-astra') and @alt = 'logo']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Assist - Astra Motor Integrated System/img_Login Sales Office_Login_logo__37kBD.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.Login_logo__37kBD</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d2cf9b71-d663-4abf-a75c-a02b2ba1d682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Login_logo__37kBD</value>
      <webElementGuid>77b38681-5932-481f-9d18-10177665a7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/logo-astra.b80ff687.svg</value>
      <webElementGuid>dcb4bb51-b012-4c2d-a4f2-2fc69f30cfb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>58a86b6c-baf8-4ed1-bf3e-9c94029bb381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-sm-8 ant-col-md-8 ant-col-lg-8&quot;]/img[@class=&quot;Login_logo__37kBD&quot;]</value>
      <webElementGuid>bbd2360b-8298-4655-90c5-f3e900765ce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/img</value>
      <webElementGuid>4763ef31-2a7a-44cd-9666-c128de2918d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>54b0926c-f79f-4088-a720-878970e2c338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>1dc160aa-ece7-4acf-baea-c389cb3f3159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/logo-astra.b80ff687.svg' and @alt = 'logo']</value>
      <webElementGuid>ebdfceac-f0c7-4675-90c7-2ca0ea0943b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
