<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value Data Pelanggan_No. NPWP</name>
   <tag></tag>
   <elementGuidId>579b9e54-71a2-4320-80b4-88ad399d98b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[(text() = 'Data Pelanggan' or . = 'Data Pelanggan')]/following-sibling::table//td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>55093a36-b190-4de9-8f97-b33ae6c0e2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>14.277.214.4242-0</value>
      <webElementGuid>5ababefc-26aa-413c-b87f-eed80b2f1bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout&quot;]/div[@class=&quot;Layout_layout-content__UoFx4&quot;]/section[@class=&quot;ant-layout Layout_layout-transition__tp-4e Layout_collapsed__Z9C94&quot;]/section[@class=&quot;ant-layout Layout_content__95Ydx&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[1]/div[@class=&quot;layout-wrapper&quot;]/div[2]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-17&quot;]/div[@class=&quot;IncomingMonitoringDetails_content-wrapper__TOOEB&quot;]/div[@class=&quot;ReferenceDocument_consumer-data--wrapper__hi937&quot;]/div[1]/table[@class=&quot;ReferenceDocument_consumer-data--table__IEtZD&quot;]/tbody[1]/tr[1]/td[7]</value>
      <webElementGuid>f4e07089-494b-42c1-a662-fb52c047ec71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/section/section/main/div/div/div[2]/div/div/div/div/div/table/tbody/tr/td[7]</value>
      <webElementGuid>07c89a8a-855e-4115-8f83-0ddc4bea4069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta Selatan'])[1]/following::td[3]</value>
      <webElementGuid>9eb838a0-f559-40ee-97bd-915d25cdd067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jl. Gunung Sahari'])[1]/following::td[4]</value>
      <webElementGuid>f5914656-6d5a-4d54-aae9-802585efafff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Pembayaran'])[1]/preceding::td[1]</value>
      <webElementGuid>4ce47db0-77b8-4eb4-9d86-eff50f5a09b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[1]/preceding::td[1]</value>
      <webElementGuid>618b03ce-8544-48ec-afce-27c394e5e62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='14.277.214.4242-0']/parent::*</value>
      <webElementGuid>17d1eebf-4d2e-47bd-beb2-c7a7f124a833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]</value>
      <webElementGuid>c865657e-8590-4246-aa1f-7a8e9c46f1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '14.277.214.4242-0' or . = '14.277.214.4242-0')]</value>
      <webElementGuid>29247db4-7cc6-4610-b4cf-11f9b01586e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
